enhance documentation code samples for exporter
IgniteUI/help-samples-src pull request #10
Opened 2017-03-02 10:59 UTC by hanastasov

2017-03-02 11:41 UTC, tiliev approved these changes

2017-03-02 12:17 UTC, damyanpetev requested changes

2017-03-02 12:17 UTC, damyanpetev commented on HTMLSamples/grid/export-client-events.html
> +                    { headerText: "Product Name", key: "Name", dataType: "string", width: "250px" },
These should still reuse the existing(  `$$(Name)` and so on) localization strings

2017-03-02 12:17 UTC, damyanpetev commented on HTMLSamples/grid/export-client-events.html
> +					{ headerText: "Delivery Date", key: "DeliveryDate", dataType: "date", width: "200px" },
And this one should be added as new string if it's not available already

2017-03-08 15:50 UTC, damyanpetev approved these changes

2017-03-08 15:50 UTC, merged